### ISSUE TITLE
Worth noting that this project, and related projects, are not specific to GO

### ISSUE THREAD

**Issue by solvingj** [mh-cbon/go-github-release#15]
I think it's a bit unfortunate that the names of these packages and repos are all prepended with "go-".  It led me to believe that they were specific to go projects, and now I believe they are universally useful CLI tools which provide simple and streamlined utility mechanisms enabling a reasonable and unified "release" process across operating systems and programming languages. 

Is my belief correct, or is there something that is Go specific?  I will be trying to implement for C++ projects today, so I guess I'll find out.  However, if I'm correct, you may want to make that clear on the main readme (because it's really awesome).

**Comment by mh-cbon** [comment]
Yes!

I started it because i felt bad about go release process at that time,
in all cases i tried to apply unix philosophy with the power of go, so anyone can re use it anywhere.
Which actually is the opposite of what the (current) go community would do, 
see gox / goxc https://github.com/laher/goxc
(Ultimately id like a gox tool per language like that consumes smaller/generic tools like i provided)

I m _really_ happy you saw that far about it. 
I wish that helped you in a way or another
more than it was troublesome to go through (if it was).

Should it be changed, 
yes probably that d help people to figure out more quickly the good in it, 
that being said, i ll try to remain humble about it because "universal" is vast.

**Comment by solvingj** [comment]
I really like your approach.  Renaming would likely be a pain for very little value, so you can just change later if you start to see lots of uses.  Again, many thanks for contributing this, it solves a problem that was honestly completely unapproachable for an intermediate developer otherwise.

**Comment by mh-cbon** [comment]
I ll keep it open to get back on it later.
